window.UI = (() => {
  const app = () => document.getElementById('app');
  const el = (tag, cls='', html='') => { const e=document.createElement(tag); if(cls) e.className=cls; if(html) e.innerHTML=html; return e; };
  function render(){ const s = Game.load(); if(!s.selectedClass) return renderClassSelect(); renderGame(); }
  function refresh(){ if(!Game.getState()?.selectedClass) return renderClassSelect(); renderGame(); }
  function renderClassSelect(){
    app().innerHTML=''; const wrap=el('div','class-select'); const card=el('div','class-card-wrap');
    card.innerHTML='<h1>Multiplication Adventure</h1><p class="muted">Choose your class. You get one free class change later.</p>';
    const grid=el('div','class-grid');
    Object.entries(GameData.classes).forEach(([id,c])=>{ const box=el('div','class-card'); box.innerHTML=`<div class="class-icon">${c.icon}</div><h2>${c.name}</h2><div>${c.difficulty}</div><p>${c.ability}: ${c.abilityText}</p><p class="muted">HP ${c.hp} · Mana ${c.mana}</p>`; const b=el('button','','Choose '+c.name); b.onclick=()=>{Game.selectClass(id);refresh();}; box.appendChild(b); grid.appendChild(box); });
    card.appendChild(grid); wrap.appendChild(card); app().appendChild(wrap);
  }
  function renderGame(){
    const s=Game.getState(); app().innerHTML=''; const shell=el('div','game'); shell.appendChild(topBar());
    const grid=el('div','main-grid'); grid.appendChild(leftPanel()); const center=el('section','panel center-panel'); center.appendChild(el('div','panel-head','<span id="centerTitle"></span>')); center.appendChild(el('div','panel-body','')); grid.appendChild(center); grid.appendChild(rightPanel()); shell.appendChild(grid); shell.appendChild(bottomBar()); app().appendChild(shell); renderCenter();
  }
  function topBar(){ const s=Game.getState(); const c=Game.cls(); const top=el('header','topbar');
    const status=el('div','status-items'); status.innerHTML=`<span class="pill">${c.icon} ${c.name}</span><span class="pill">Area: ${s.area}</span><span class="pill">Coins: ${s.coins}</span><span class="pill">${bossKeyText()}</span>`;
    const nav=el('div','nav-items'); const town=btn('Town','secondary',()=>{const r=Game.goTown(); if(!r.ok) showModal('Locked',r.msg); refresh();}); town.disabled=s.inBoss; nav.append(town,btn('Map','secondary',()=>showMap()),btn('Mastery','secondary',()=>showMastery()));
    top.append(status,nav); return top;
  }
  function bottomBar(){ const s=Game.getState(); const sm=Mastery.summary(s.mastery); const bar=el('footer','bottombar'); const items=el('div','bottom-items'); items.innerHTML=`<span class="pill">HP: ${'♥'.repeat(Math.max(0,s.hp))}</span><span class="pill">Mana: ${'✦'.repeat(Math.max(0,s.mana))}</span><span class="pill">Level ${s.level}</span><span class="pill">XP ${s.xp}/100</span><span class="pill">Streak ${s.session?.streak||0}</span><span class="pill">Accuracy ${s.session?.roundAccuracy||sm.accuracy}%</span><span class="pill">Mastered ${sm.mastered}/121</span>`; bar.appendChild(items); return bar; }
  function leftPanel(){ const s=Game.getState(); const c=Game.cls(); const p=el('aside','panel left-panel'); p.appendChild(el('div','panel-head','Hero')); const body=el('div','panel-body'); const st=Game.stats();
    body.innerHTML=`<div class="hero-portrait">${c.icon}</div><h3>${c.name} ${c.difficulty}</h3><p><b>${c.ability}</b><br><span class="muted">${c.abilityText}</span></p><h4>Gear</h4>`;
    const gear=el('div','gear-list'); ['weapon','head','body','legs','pet','aura','frame','cosmetic'].forEach(slot=>{const item=Game.getItem(s.equipped[slot]); gear.appendChild(row(slot, item?item.name:'None'));}); body.appendChild(gear);
    body.appendChild(el('h4','','Stats')); const stats=el('div','stat-list'); Object.entries(st).forEach(([k,v])=>stats.appendChild(row(k,v))); body.appendChild(stats);
    body.append(btn('Inventory','secondary',()=>showInventory()), btn('Change Class','secondary',()=>showClassChange()), btn('Profile','secondary',()=>showProfile())); p.appendChild(body); return p;
  }
  function rightPanel(){ const s=Game.getState(); const p=el('aside','panel right-panel'); p.appendChild(el('div','panel-head','Quests + Coach')); const body=el('div','panel-body'); body.innerHTML='<h4>Quest Log</h4>'; const ql=el('div','quest-list');
    GameData.quests.forEach(q=>{const prog=s.quests.progress[q.id]||0; const done=prog>=q.target; const claimed=s.quests.claimed[q.id]; const item=el('div','town-card'); item.innerHTML=`<b>${q.title}</b><span>${prog}/${q.target}</span><span class="muted">Reward: ${q.reward} coins</span>`; if(done&&!claimed)item.appendChild(btn('Claim','',()=>{const r=Game.claimQuest(q.id); showToast(r.msg); refresh();})); if(claimed)item.appendChild(el('span','good','Claimed')); ql.appendChild(item);}); body.appendChild(ql);
    body.appendChild(el('h4','','Coach')); const coach=el('div','town-card',coachText()); body.appendChild(coach); p.appendChild(body); return p;
  }
  function row(k,v){ const r=el('div','small-row'); r.innerHTML=`<span>${title(k)}</span><b>${v}</b>`; return r; }
  function btn(text, cls='', fn=null){ const b=el('button',cls,text); if(fn)b.onclick=fn; return b; }
  function title(t){return String(t).replace(/([A-Z])/g,' $1').replace(/^./,m=>m.toUpperCase());}
  function center(titleText){ document.getElementById('centerTitle').textContent=titleText; const b=document.querySelector('.center-panel .panel-body'); b.innerHTML=''; return b; }
  function renderCenter(){ const s=Game.getState(); if(s.mode==='town') return showTown(); if(s.mode==='battle'||s.mode==='training'||s.mode==='boss') return showQuestion(); if(s.mode==='results') return showResults(); return showTown(); }
  function showTown(){ const b=center('Town'); b.innerHTML='<p class="muted">Choose what to do next.</p>'; const grid=el('div','town-grid');
    const cards=[['Training Area','Practice weak facts anytime.',()=>{Game.startTraining();refresh();}],['Adventure Map','Choose an area or boss.',()=>showMap()],['Class Shop','Buy class gear and cosmetics.',()=>showShop()],['Inventory','Manage gear and cosmetics.',()=>showInventory()],['Quest Board','View and claim quests.',()=>showQuests()],['Current Mastery','View the 0–10 mastery table.',()=>showMastery()],['Personal Records','See your best records.',()=>showRecords()],['Settings / Reset','Reset the game with confirmation.',()=>showReset()]];
    cards.forEach(([h,p,fn])=>{const c=el('div','town-card'); c.innerHTML=`<h3>${h}</h3><p class="muted">${p}</p>`; c.appendChild(btn('Open','',fn)); grid.appendChild(c);}); b.appendChild(grid);
  }
  function showQuestion(){ const s=Game.getState(), q=s.session.question; const b=center(s.mode==='training'?'Training Area':s.mode==='boss'?'Boss Battle':'Adventure');
    const box=el('div','question-box'); box.innerHTML=`<div class="pill">Question ${s.session.total+1}/${s.session.target}${s.mode==='boss'?` · Boss HP ${s.session.bossHp}`:''}</div><div class="question">${q.a} × ${q.b} = ?</div>`;
    const answers=el('div','answers'); s.session.choices.forEach(v=>{const ab=btn(String(v),'',()=>manualAnswer(v)); if(s.session.answered) ab.disabled=true; answers.appendChild(ab);}); box.appendChild(answers);
    if(s.session.answered){ const fb=el('div','feedback '+(s.session.lastCorrect?'good':'bad'), s.session.lastCorrect?'Correct!':'Not yet. Correct answer: '+q.product); box.appendChild(fb); box.appendChild(btn(Game.getState().session.total>=Game.getState().session.target || (s.mode==='boss'&&(s.session.bossHp<=0||s.hp<=0))?'Finish':'Next Question','',()=>{Game.continueAfterAnswer();refresh();})); }
    b.appendChild(box); if(s.mode==='boss') b.appendChild(el('p','muted','Class changes and Town travel are locked during boss battles.'));
  }
  function manualAnswer(v){ Game.submitAnswer(v); refresh(); }
  function showResults(){ const s=Game.getState(), r=s.session.result; const b=center('Results'); const box=el('div','question-box'); box.innerHTML=`<h2>${r.msg}</h2><p>Correct: <b>${r.correct}/${r.total}</b></p><p>Accuracy: <b>${r.accuracy}%</b></p><p>Coins earned: <b>${r.coins}</b></p><p>Facts improved: <b>${r.improved}</b></p>`; box.append(btn('Back to Town','',()=>{Game.goTown();refresh();}), btn('Train Weak Facts','secondary',()=>{Game.startTraining();refresh();})); b.appendChild(box); }
  function showMap(){ const b=center('Adventure Map'); const grid=el('div','area-grid'); GameData.areas.forEach(area=>{ const p=Game.getState().progress[area.id]; const card=el('div','area-card'); card.innerHTML=`<h3>${area.name}</h3><p>Focus: ${area.focus.join(', ')}</p><p>${p.unlocked?'Unlocked':'Locked'}</p><p>Rounds: ${p.rounds}/${area.requiredRounds} · Best: ${p.bestAccuracy}%/${area.requiredAccuracy}%</p><p>Boss Key: ${p.key?'Ready':'Not ready'} · Boss: ${p.bossDefeated?'Defeated':'Waiting'}</p>`; const start=btn('Start Area','',()=>{const r=Game.startArea(area.id); if(!r.ok) showModal('Area Locked',r.msg); refresh();}); start.disabled=!p.unlocked; const boss=btn('Fight Boss','secondary',()=>{const r=Game.startBoss(area.id); if(!r.ok) showModal('Boss Locked',r.msg); refresh();}); boss.disabled=!p.unlocked || !p.key; card.append(start,boss); grid.appendChild(card); }); b.appendChild(grid); }
  function showShop(){ const b=center('Class Shop'); let selected=null; const tabs=el('div','tabs'); ['all','weapon','head','body','legs','pet','aura','frame','cosmetic'].forEach(t=>tabs.appendChild(btn(title(t),'secondary',()=>draw(t)))); b.appendChild(tabs); const list=el('div','item-grid'); const preview=el('div','item-preview hidden'); b.append(list,preview,btn('Back to Town','secondary',()=>showTown()));
    function draw(type='all'){ list.innerHTML=''; preview.classList.add('hidden'); preview.innerHTML=''; selected=null; Game.shopItems().filter(i=>type==='all'||i.slot===type||i.type===type).forEach(item=>{ const c=el('div','item-card'); c.innerHTML=`<b>${item.name}</b><span>${item.rarity} · ${item.cost} coins</span><span class="muted">${item.desc}</span><span>${Game.owned(item.id)?'Owned':'Available'}</span>`; c.appendChild(btn('Preview','',()=>select(item))); list.appendChild(c); }); }
    function select(item){ selected=item; preview.classList.remove('hidden'); preview.innerHTML=`<h3>${item.name}</h3><p>${item.desc}</p><p>Class: ${item.cls.join(', ')}</p><p>Stats: ${Object.entries(item.stats||{}).map(([k,v])=>`${k}+${v}`).join(', ')||'Cosmetic only'}</p>`; const buy=btn(Game.owned(item.id)?'Owned':'Buy','',()=>{const r=Game.buyItem(item.id); if(r.ok) askEquip(item); else showModal('Shop',r.msg); draw('all');}); buy.disabled=Game.owned(item.id); preview.appendChild(buy); preview.appendChild(btn('Close Preview','secondary',()=>{preview.classList.add('hidden'); selected=null;})); }
    draw('all');
  }
  function askEquip(item){ showModal('Item Bought',`${item.name} was added to your inventory. Equip it now?`, [ ['Equip',()=>{Game.equipItem(item.id); closeModal(); refresh();}], ['Later',()=>{closeModal(); refresh();}, 'secondary'] ]); }
  function showInventory(){ const b=center('Inventory'); const s=Game.getState(); b.innerHTML='<p class="muted">Equip and unequip owned items. Wrong-class items stay locked.</p><h3>Equipped</h3>'; const eq=el('div','inventory-grid'); Object.keys(s.equipped).forEach(slot=>{const item=Game.getItem(s.equipped[slot]); const c=el('div','item-card'); c.innerHTML=`<b>${title(slot)}</b><span>${item?item.name:'Empty'}</span>`; const u=btn('Unequip','secondary',()=>{Game.unequip(slot);showInventory();}); u.disabled=!item; c.appendChild(u); eq.appendChild(c);}); b.appendChild(eq); b.appendChild(el('h3','','Owned Items')); const grid=el('div','inventory-grid'); if(!s.inventory.length) grid.innerHTML='<p>No items yet. Visit the shop.</p>'; s.inventory.forEach(id=>{ const item=Game.getItem(id); const locked=!Game.allowed(item); const equipped=Object.values(s.equipped).includes(id); const c=el('div','item-card'); c.innerHTML=`<b>${item.name}</b><span>${item.slot}</span><span class="muted">${item.desc}</span><span>${locked?'Locked for current class':equipped?'Equipped':'Ready'}</span>`; const e=btn('Equip','',()=>{const r=Game.equipItem(id); if(!r.ok) showModal('Locked',r.msg); showInventory();}); e.disabled=locked||equipped; c.appendChild(e); grid.appendChild(c);}); b.appendChild(grid); b.appendChild(btn('Back to Town','secondary',()=>showTown())); }
  function showMastery(){ const s=Game.getState(); const sum=Mastery.summary(s.mastery); const b=center('Current Mastery'); b.classList.add('scroll-all'); const wrap=el('div','mastery-wrap'); const summary=el('div','mastery-summary'); [['Attempts',sum.attempts],['Correct',sum.correct],['Accuracy',sum.accuracy+'%'],['Mastered',sum.mastered+'/121'],['Strong',sum.strong],['Needs Practice',sum.needs],['Practiced',sum.practiced]].forEach(([k,v])=>summary.appendChild(el('div','stat-card',`<b>${v}</b><br><span>${k}</span>`))); wrap.appendChild(summary); wrap.appendChild(el('div','legend','<span class="m0">New</span><span class="m1">Needs Practice</span><span class="m2">Getting Better</span><span class="m3">Strong</span><span class="m4">Mastered</span>'));
    const table=el('table','mastery-table'); let html='<tr><th>×</th>'; for(let i=0;i<=10;i++) html+=`<th>${i}</th>`; html+='</tr>'; for(let a=0;a<=10;a++){ html+=`<tr><th>${a}</th>`; for(let b2=0;b2<=10;b2++){const f=s.mastery[Mastery.key(a,b2)]; html+=`<td class="m${f.level}" title="${a}×${b2}: ${Mastery.levels[f.level]}">${a*b2}</td>`;} html+='</tr>'; } table.innerHTML=html; wrap.appendChild(table); wrap.append(btn('Train Weak Facts','',()=>{Game.startTraining();refresh();}), btn('Back to Town','secondary',()=>showTown())); b.appendChild(wrap); }
  function showQuests(){ const b=center('Quest Board'); b.innerHTML='<p class="muted">Complete quests to earn coins and prepare for bosses.</p>'; const list=el('div','quest-list'); const s=Game.getState(); GameData.quests.forEach(q=>{ const prog=s.quests.progress[q.id]||0; const done=prog>=q.target; const claimed=s.quests.claimed[q.id]; const card=el('div','town-card'); card.innerHTML=`<h3>${q.title}</h3><p>Progress: ${prog}/${q.target}</p><p class="muted">Reward: ${q.reward} coins</p>`; if(done&&!claimed) card.appendChild(btn('Claim Reward','',()=>{ const r=Game.claimQuest(q.id); showModal('Quest',r.msg); refresh(); })); else if(claimed) card.appendChild(el('span','good','Claimed')); else card.appendChild(el('span','warn','Not complete yet')); list.appendChild(card); }); b.appendChild(list); b.appendChild(btn('Back to Town','secondary',()=>showTown())); }
  function showProfile(){ const b=center('Hero Profile'); const s=Game.getState(), c=Game.cls(), sm=Mastery.summary(s.mastery); b.innerHTML=`<div class="question-box"><div class="class-icon">${c.icon}</div><h2>${c.name}</h2><p>${c.difficulty}</p><p>Level ${s.level} · Coins ${s.coins}</p><p>Mastered facts: ${sm.mastered}/121</p><p>Bosses defeated: ${s.records.bossesDefeated}</p></div>`; b.append(btn('Inventory','',()=>showInventory()),btn('Current Mastery','secondary',()=>showMastery()),btn('Settings / Reset','danger',()=>showReset())); }
  function showRecords(){ const b=center('Personal Records'); const r=Game.getState().records; const grid=el('div','mastery-summary'); Object.entries(r).forEach(([k,v])=>grid.appendChild(el('div','stat-card',`<b>${v}</b><br><span>${title(k)}</span>`))); b.appendChild(grid); b.appendChild(btn('Back to Town','secondary',()=>showTown())); }
  function showClassChange(){ const b=center('Change Class'); if(!Game.canChangeClass()) {b.innerHTML='<p>Class changes are only available in Town.</p>'; return;} b.innerHTML=`<p>${Game.getState().freeClassChange?'Your next class change is free.':'Class change fee: 25 coins.'}</p>`; const grid=el('div','class-grid'); Object.entries(GameData.classes).forEach(([id,c])=>{const card=el('div','class-card'); card.innerHTML=`<div class="class-icon">${c.icon}</div><h3>${c.name}</h3><p>${c.difficulty}</p><p>${c.ability}</p>`; const bb=btn('Change to '+c.name,'',()=>{const r=Game.changeClass(id); showModal('Class Change',r.msg||'Class changed.'); refresh();}); bb.disabled=id===Game.getState().selectedClass; card.appendChild(bb); grid.appendChild(card);}); b.appendChild(grid); }
  function showReset(){ showModal('Reset Game','This will erase class selection, coins, gear, quests, boss keys, records, and mastery progress. This cannot be undone.', [['Cancel',closeModal,'secondary'],['Reset Everything',()=>{Game.reset();closeModal();refresh();},'danger']]); }
  function bossKeyText(){ const s=Game.getState(); if(s.currentArea){ const p=s.progress[s.currentArea]; return `Boss Key: ${p.key?'Ready':'Not Ready'}`;} return 'Boss Key: —'; }
  function coachText(){ const s=Game.getState(); const weak=Mastery.weakFacts(s.mastery,1)[0]; if(s.mode==='boss') return 'Boss Rule: correct answers damage the boss; wrong answers cost HP.'; if(s.mode==='battle') return 'Use the fact strategy you know. Check your product before choosing.'; if(s.mode==='training'&&weak) return `Training Focus: ${weak.a} × ${weak.b}`; if(weak) return `Recommended: train ${weak.a} × ${weak.b} before a boss.`; return 'Recommended: start an area or complete a quest.'; }
  function showModal(title,msg,actions=null){ closeModal(); const back=el('div','modal-backdrop'); back.id='modal'; const m=el('div','modal'); m.innerHTML=`<h2>${title}</h2><p>${msg}</p>`; const a=el('div','modal-actions'); (actions||[['OK',closeModal,'']]).forEach(([t,fn,cls])=>a.appendChild(btn(t,cls||'',fn))); m.appendChild(a); back.appendChild(m); document.body.appendChild(back); }
  function closeModal(){ const m=document.getElementById('modal'); if(m)m.remove(); }
  function showToast(msg){ showModal('Notice',msg); }
  return { render, refresh };
})();
document.addEventListener('DOMContentLoaded', UI.render);
