const SAVE_KEY='multQuestRPG_v1_localOnly';
const app=document.getElementById('app');
const modalRoot=document.getElementById('modal-root');
const FACT_MAX=12;
const CLASSES={
 knight:{name:'Knight',icon:'🛡️',stars:2,desc:'The safest hero. High health, stronger shields, and mistakes hurt less.',hp:130,coinBoost:0,crit:0.04,powerDiscount:0,shieldBonus:1},
 archer:{name:'Archer',icon:'🏹',stars:3,desc:'The speed hero. Earns more coins for fast answers and lands more critical hits.',hp:100,coinBoost:.25,crit:0.18,powerDiscount:0,shieldBonus:0},
 mage:{name:'Mage',icon:'🔮',stars:4,desc:'The strategy hero. Powers cost less, time freeze lasts longer, and hints are stronger.',hp:95,coinBoost:0,crit:0.08,powerDiscount:.25,shieldBonus:0}
};
const AREAS=[
 {id:0,name:'Apprentice Forest',stars:1,facts:[0,1,2,3],boss:'Forest Goblin',questions:10},
 {id:1,name:'Wolfwood Trail',stars:2,facts:[4,5],boss:'Alpha Wolf',questions:12},
 {id:2,name:'Ironkeep Mountains',stars:3,facts:[6,7],boss:'Stone Giant',questions:14},
 {id:3,name:'Dragonfire Wastes',stars:4,facts:[8,9],boss:'Fire Dragon',questions:16},
 {id:4,name:'Citadel of Legends',stars:5,facts:[10,11,12],boss:'Dragon of the Tables',questions:18},
 {id:5,name:'Hall of Champions',stars:5,facts:[0,1,2,3,4,5,6,7,8,9,10,11,12],boss:'Mastery Wyrm',questions:20,endgame:true}
];
const GEAR=[
 {id:'wood_sword',name:'Wood Sword',slot:'weapon',cost:40,rarity:'Common',bonus:{damage:2}},
 {id:'iron_sword',name:'Iron Sword',slot:'weapon',cost:120,rarity:'Uncommon',bonus:{damage:5}},
 {id:'focus_staff',name:'Focus Staff',slot:'weapon',cost:160,rarity:'Rare',bonus:{xp:0.1,damage:3}},
 {id:'cloth_hood',name:'Cloth Hood',slot:'helmet',cost:35,rarity:'Common',bonus:{hp:5}},
 {id:'iron_helm',name:'Iron Helm',slot:'helmet',cost:100,rarity:'Uncommon',bonus:{hp:12}},
 {id:'leather_vest',name:'Leather Vest',slot:'body',cost:60,rarity:'Common',bonus:{hp:10}},
 {id:'steel_armor',name:'Steel Armor',slot:'body',cost:180,rarity:'Rare',bonus:{hp:25}},
 {id:'soft_boots',name:'Soft Boots',slot:'legs',cost:50,rarity:'Common',bonus:{speedCoin:0.1}},
 {id:'ranger_greaves',name:'Ranger Greaves',slot:'legs',cost:140,rarity:'Rare',bonus:{speedCoin:0.2,hp:8}}
];
const POWERS={shield:{name:'Shield',cost:50,desc:'Blocks the next wrong answer.'},double:{name:'Double Points',cost:60,desc:'Doubles points for the next question.'},freeze:{name:'Time Freeze',cost:40,desc:'Removes time pressure for the next question.'},skip:{name:'Skip',cost:35,desc:'Skip one question without penalty.'}};
function blankMastery(){const m={};for(let a=0;a<=FACT_MAX;a++){for(let b=0;b<=FACT_MAX;b++){m[`${a}x${b}`]={attempts:0,correct:0,incorrect:0,totalTime:0,last:0,recentMiss:0};}}return m;}
function newState(){return {created:true,nickname:'',classKey:null,level:1,xp:0,coins:100,score:0,bestScore:0,bestStreak:0,streak:0,unlockedArea:0,current:null,inventory:['wood_sword'],equipped:{weapon:'wood_sword',helmet:null,body:null,legs:null},badges:[],powers:{shield:0,double:0,freeze:0,skip:0},active:{double:false,freeze:false,shield:false},leaderboard:[],mastery:blankMastery(),recentFacts:[],settings:{sound:false,accessibility:false}}}
let S=load();let answerInput=null;let questionStart=0;
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify(S));}
function load(){try{const raw=localStorage.getItem(SAVE_KEY);if(raw){const s=JSON.parse(raw); if(!s.mastery) s.mastery=blankMastery(); return s;}}catch(e){} return newState();}
function stars(n){return '★'.repeat(n)+'☆'.repeat(5-n)}
function gearBonus(){const out={hp:0,damage:0,xp:0,speedCoin:0};Object.values(S.equipped||{}).forEach(id=>{const g=GEAR.find(x=>x.id===id); if(g) Object.entries(g.bonus).forEach(([k,v])=>out[k]=(out[k]||0)+v);});return out;}
function heroHP(){const c=CLASSES[S.classKey]||CLASSES.knight;return c.hp+(gearBonus().hp||0)}
function xpNeeded(){return S.level*100}
function addXP(n){const b=gearBonus();S.xp+=Math.round(n*(1+(b.xp||0)));while(S.xp>=xpNeeded()){S.xp-=xpNeeded();S.level++;awardBadge('Level '+S.level);} }
function awardBadge(name){if(!S.badges.includes(name)){S.badges.push(name);toast('Badge earned: '+name)}}
function toast(msg){console.log(msg)}
function screen(html){app.innerHTML=html}
function mainMenu(){save();const has=S.nickname&&S.classKey;screen(`<div class="wrap"><div class="card"><h1 class="title">⚔️ Multiplication Quest RPG</h1><p>A local-only multiplication adventure. Defeat bosses by mastering facts.</p><div class="warning">⚠️ Use a nickname only. Do not use your real name, school, address, phone number, email, or personal information. Progress stays only on this device/browser.</div></div>${has?menuExisting():menuNew()}</div>`)}
function menuExisting(){return `<div class="card"><h2>Welcome back, ${escapeHtml(S.nickname)} the ${CLASSES[S.classKey].name}</h2><div class="grid"><div class="stat">Level: <b>${S.level}</b><br>Coins: <b>${S.coins}</b><br>Score: <b>${S.score}</b></div><div class="stat">Best Score: <b>${S.bestScore}</b><br>Best Streak: <b>${S.bestStreak}</b><br>Unlocked: <b>${AREAS[S.unlockedArea].name}</b></div></div><div class="row"><button onclick="continueAdventure()">Continue Adventure</button><button class="secondary" onclick="worldMap()">World Map</button><button class="secondary" onclick="heroScreen()">Hero</button><button class="secondary" onclick="localLeaderboard()">Local Leaderboard</button><button class="ghost" onclick="instructions()">Instructions</button></div></div><div class="card"><button class="danger" onclick="confirmReset()">Reset Local Save</button></div>`}
function menuNew(){return `<div class="card"><h2>Start New Adventure</h2><label>Nickname only:</label><input id="nick" maxlength="16" placeholder="Example: StarFox" class="answerBox" style="font-size:22px;text-align:left;max-width:100%"><h3>Choose Your Hero</h3><div class="grid">${Object.entries(CLASSES).map(([k,c])=>`<div class="card"><h2>${c.icon} ${c.name}</h2><div class="stars">${stars(c.stars)}</div><p>${c.desc}</p><button onclick="startNew('${k}')">Choose ${c.name}</button></div>`).join('')}</div></div>`}
function startNew(k){const nick=document.getElementById('nick').value.trim().replace(/[^a-zA-Z0-9 _-]/g,'').slice(0,16); if(!nick){alert('Choose a nickname. Do not use your real name.');return} S=newState();S.nickname=nick;S.classKey=k;awardBadge('First Steps');save();worldMap();}
function worldMap(){screen(`<div class="wrap"><div class="card row space"><h1>🌎 World Map</h1><button class="secondary" onclick="mainMenu()">Main Menu</button></div><div class="grid">${AREAS.map(a=>`<div class="card area ${a.id>S.unlockedArea?'locked':''}"><h2>${a.name}</h2><div class="stars">${stars(a.stars)}</div><p>Facts: ${a.endgame?'Adaptive review':a.facts.join('s, ')+'s'}</p><p>Boss: <b>${a.boss}</b></p>${a.id<=S.unlockedArea?`<button onclick="enterArea(${a.id})">Enter Area</button>`:'<button disabled>Locked</button>'}</div>`).join('')}</div></div>`)}
function continueAdventure(){if(S.current) renderGame(); else enterArea(Math.min(S.unlockedArea,AREAS.length-1));}
function enterArea(id){const a=AREAS[id];S.current={area:id,q:0,phase:'questions',bossHP:100,heroHP:heroHP(),lastQuestion:null};save();renderGame();}
function renderGame(){const c=S.current;if(!c){mainMenu();return} const a=AREAS[c.area]; if(c.phase==='boss') return renderBoss(); const fact=chooseFact(a); c.lastQuestion=fact; questionStart=Date.now(); save();screen(hud()+`<div class="wrap"><div class="card"><div class="row space"><h2>${a.name}</h2><button class="secondary" onclick="confirmQuit()">Main Menu</button></div><p>Question ${c.q+1} of ${a.questions}</p><div class="question">${fact.a} × ${fact.b}</div><div class="row" style="justify-content:center"><input id="answer" class="answerBox" inputmode="numeric" pattern="[0-9]*" autocomplete="off"><button onclick="submitAnswer()">Submit</button></div><p class="kbdNote" style="text-align:center">Press Enter to submit. The answer box should stay focused on mobile.</p><div class="row" style="justify-content:center"><button class="ghost" onclick="usePower('shield')">Shield (${S.powers.shield})</button><button class="ghost" onclick="usePower('double')">Double (${S.powers.double})</button><button class="ghost" onclick="usePower('freeze')">Freeze (${S.powers.freeze})</button><button class="ghost" onclick="usePower('skip')">Skip (${S.powers.skip})</button></div></div></div>`);focusAnswer();}
function hud(){const b=gearBonus();return `<div class="hud"><div class="wrap row space"><span>${CLASSES[S.classKey].icon} ${escapeHtml(S.nickname)} Lv.${S.level}</span><span>XP ${S.xp}/${xpNeeded()}</span><span>🪙 ${S.coins}</span><span>Score ${S.score}</span><span>Streak ${S.streak}</span></div></div>`}
function focusAnswer(){setTimeout(()=>{answerInput=document.getElementById('answer'); if(answerInput){answerInput.focus({preventScroll:true}); answerInput.onkeydown=e=>{if(e.key==='Enter')submitAnswer();};}},80);setTimeout(()=>{if(answerInput)answerInput.focus({preventScroll:true});},240)}
function chooseFact(area){let pool=[];const facts=area.endgame?Array.from({length:13},(_,i)=>i):area.facts;for(const a of facts){for(let b=0;b<=FACT_MAX;b++){pool.push({a,b,key:`${a}x${b}`}); if(a!==b) pool.push({a:b,b:a,key:`${b}x${a}`});}}
 const recent=new Set(S.recentFacts.slice(-8)); let weighted=[]; pool.forEach(f=>{if(recent.has(f.key)&&pool.length>12)return; const lvl=masteryLevel(f.key); const weights={Automatic:1,Mastered:2,Proficient:4,Developing:8,Learning:12,'Not Introduced':10}; let w=weights[lvl]||6; if(area.endgame && (lvl==='Learning'||lvl==='Developing')) w+=10; for(let i=0;i<w;i++) weighted.push(f);}); return weighted[Math.floor(Math.random()*weighted.length)]||pool[Math.floor(Math.random()*pool.length)];}
function masteryLevel(key){const m=S.mastery[key]||{attempts:0,correct:0,totalTime:0}; if(m.attempts===0)return 'Not Introduced'; const acc=m.correct/m.attempts; const avg=m.correct?m.totalTime/m.correct:99; if(m.attempts>=20&&acc>=.95&&avg<3)return 'Automatic'; if(m.attempts>=10&&acc>=.9)return 'Mastered'; if(m.attempts>=5&&acc>=.8)return 'Proficient'; if(acc>=.6)return 'Developing'; return 'Learning';}
function submitAnswer(){const inp=document.getElementById('answer');if(!inp)return;const val=Number(inp.value);const f=S.current.lastQuestion;const correct=val===f.a*f.b;const responseTime=(Date.now()-questionStart)/1000;recordFact(f.key,correct,responseTime);let pts=correct?10:0;let coins=correct?5:0;let msg='';const cls=CLASSES[S.classKey];if(correct){if(responseTime<3){coins+=Math.round(3*(1+cls.coinBoost+(gearBonus().speedCoin||0)));msg+='Fast bonus! '} if(S.active.double){pts*=2;S.active.double=false;msg+='Double points! '} if(Math.random()<cls.crit){pts+=10;msg+='Critical hit! '} S.streak++; S.score+=pts; S.coins+=coins; addXP(10); if(S.streak>=10)awardBadge('10 Correct Streak');}else{if(S.active.shield||S.powers.shield>0){if(S.active.shield)S.active.shield=false; else S.powers.shield--; msg+='Shield blocked the mistake. ';} else {S.streak=0;}}
S.bestScore=Math.max(S.bestScore,S.score);S.bestStreak=Math.max(S.bestStreak,S.streak);S.recentFacts.push(f.key);S.recentFacts=S.recentFacts.slice(-15);save();showResult(correct,pts,coins,msg,f,val);}
function recordFact(key,correct,time){if(!S.mastery[key])S.mastery[key]={attempts:0,correct:0,incorrect:0,totalTime:0,last:0,recentMiss:0};const m=S.mastery[key];m.attempts++;m.last=Date.now(); if(correct){m.correct++;m.totalTime+=time;m.recentMiss=0}else{m.incorrect++;m.recentMiss++}}
function showResult(correct,pts,coins,msg,f,val){modalRoot.innerHTML=`<div class="modalOverlay"><div class="modal"><div class="${correct?'bigGood':'bigBad'}">${correct?'Correct!':'Try again next time'}</div><h2>${f.a} × ${f.b} = ${f.a*f.b}</h2><p>Your answer: ${Number.isNaN(val)?'blank':val}</p><p>+${pts} points · +${coins} coins ${msg}</p><div class="row"><button onclick="nextQuestion()">${S.current.q+1>=AREAS[S.current.area].questions?'Face Boss':'Next Question'}</button><button class="secondary" onclick="openShop()">Shop</button><button class="secondary" onclick="heroScreen(true)">Hero</button><button class="ghost" onclick="closeModal();mainMenu()">Main Menu</button></div></div></div>`}
function nextQuestion(){closeModal();const a=AREAS[S.current.area];S.current.q++; if(S.current.q>=a.questions){S.current.phase='boss';S.current.bossHP=100;S.current.heroHP=heroHP();save();bossIntro();}else{save();renderGame();}}
function bossIntro(){const a=AREAS[S.current.area];modalRoot.innerHTML=`<div class="modalOverlay"><div class="modal"><h1>⚠️ Boss Battle</h1><h2>${a.boss}</h2><p>The boss will use a mix of this area's facts and facts you are still practicing.</p><button onclick="closeModal();renderBoss()">Fight Boss</button></div></div>`}
function renderBoss(){const a=AREAS[S.current.area];const fact=chooseFact({...a,endgame:true});S.current.lastQuestion=fact;questionStart=Date.now();save();screen(hud()+`<div class="wrap"><div class="card boss"><div class="row space"><h2>👹 ${a.boss}</h2><button class="secondary" onclick="confirmQuit()">Main Menu</button></div><p>Boss HP</p><div class="bar"><span style="width:${S.current.bossHP}%"></span></div><p>Hero HP</p><div class="bar"><span style="width:${Math.max(0,S.current.heroHP/heroHP()*100)}%"></span></div><div class="question">${fact.a} × ${fact.b}</div><div class="row" style="justify-content:center"><input id="answer" class="answerBox" inputmode="numeric" pattern="[0-9]*" autocomplete="off"><button onclick="submitBossAnswer()">Strike</button></div></div></div>`);focusAnswer();}
function submitBossAnswer(){const inp=document.getElementById('answer');const val=Number(inp.value);const f=S.current.lastQuestion;const correct=val===f.a*f.b;const responseTime=(Date.now()-questionStart)/1000;recordFact(f.key,correct,responseTime);const dmgBase=14+(gearBonus().damage||0)+Math.floor(S.level/2);let msg='';if(correct){let dmg=dmgBase;if(Math.random()<CLASSES[S.classKey].crit){dmg*=2;msg='Critical hit! '}S.current.bossHP=Math.max(0,S.current.bossHP-dmg);S.score+=15;S.coins+=8;S.streak++;addXP(15);}else{let hurt=18;if(S.classKey==='knight')hurt=10;if(S.active.shield||S.powers.shield>0){if(S.active.shield)S.active.shield=false;else S.powers.shield--;hurt=0;msg='Shield blocked damage! '}S.current.heroHP=Math.max(0,S.current.heroHP-hurt);S.streak=0;}S.bestScore=Math.max(S.bestScore,S.score);S.bestStreak=Math.max(S.bestStreak,S.streak);S.recentFacts.push(f.key);S.recentFacts=S.recentFacts.slice(-15);save();if(S.current.bossHP<=0)return bossWin();if(S.current.heroHP<=0)return bossLose();modalRoot.innerHTML=`<div class="modalOverlay"><div class="modal"><div class="${correct?'bigGood':'bigBad'}">${correct?'Hit!':'Boss Strikes!'}</div><h2>${f.a} × ${f.b} = ${f.a*f.b}</h2><p>${msg}</p><div class="row"><button onclick="closeModal();renderBoss()">Next Strike</button><button class="secondary" onclick="openShop()">Shop</button><button class="ghost" onclick="closeModal();mainMenu()">Main Menu</button></div></div></div>`}
function bossWin(){const a=AREAS[S.current.area];awardBadge(`${a.boss} Defeated`);S.coins+=50;addXP(50);if(S.current.area<S.unlockedArea+1){} if(S.current.area<AREAS.length-1)S.unlockedArea=Math.max(S.unlockedArea,S.current.area+1);pushLeader();S.current=null;save();modalRoot.innerHTML=`<div class="modalOverlay"><div class="modal"><h1 class="bigGood">Victory!</h1><h2>${a.boss} defeated</h2><p>+50 coins. New area unlocked if available.</p><button onclick="closeModal();worldMap()">World Map</button></div></div>`}
function bossLose(){S.current.phase='boss';S.current.heroHP=heroHP();S.current.bossHP=Math.max(50,S.current.bossHP);save();modalRoot.innerHTML=`<div class="modalOverlay"><div class="modal"><h1 class="bigBad">Retreat!</h1><p>Your hero recovers. The boss keeps some damage.</p><button onclick="closeModal();renderBoss()">Try Again</button><button class="secondary" onclick="closeModal();mainMenu()">Main Menu</button></div></div>`}
function usePower(p){if(S.powers[p]<=0){alert('You do not have this power. Visit the shop.');focusAnswer();return} if(p==='skip'){S.powers.skip--;save();nextQuestion();return} S.powers[p]--;S.active[p]=true;save();alert(POWERS[p].name+' activated.');focusAnswer();}
function openShop(){const cls=CLASSES[S.classKey];modalRoot.innerHTML+=`<div class="modalOverlay" id="shop"><div class="modal"><h1>🛒 Shop</h1><p>Coins: ${S.coins}</p><h2>Powers</h2>${Object.entries(POWERS).map(([k,p])=>{const cost=Math.round(p.cost*(1-cls.powerDiscount));return `<div class="gearSlot"><b>${p.name}</b> — ${cost} coins<br><span class="muted">${p.desc}</span><br><button onclick="buyPower('${k}',${cost})">Buy</button></div>`}).join('')}<h2>Gear</h2>${GEAR.map(g=>`<div class="gearSlot"><b>${g.name}</b> (${g.rarity}) — ${g.cost} coins<br>Slot: ${g.slot}<br>${S.inventory.includes(g.id)?`<button onclick="equip('${g.id}')">Equip</button>`:`<button onclick="buyGear('${g.id}')">Buy</button>`}</div>`).join('')}<button class="secondary" onclick="closeShop()">Back to Results/Game</button></div></div>`}
function closeShop(){const el=document.getElementById('shop'); if(el)el.remove(); focusAnswer();}
function buyPower(k,cost){if(S.coins<cost)return alert('Not enough coins.');S.coins-=cost;S.powers[k]++;save();closeShop();openShop();}
function buyGear(id){const g=GEAR.find(x=>x.id===id);if(!g||S.coins<g.cost)return alert('Not enough coins.');S.coins-=g.cost;S.inventory.push(id);save();closeShop();openShop();}
function equip(id){const g=GEAR.find(x=>x.id===id);if(!g)return;S.equipped[g.slot]=id;save();closeShop();openShop();}
function heroScreen(fromModal=false){const b=gearBonus();const equipped=Object.entries(S.equipped).map(([slot,id])=>`<div class="gearSlot"><b>${slot}</b>: ${id?GEAR.find(g=>g.id===id)?.name:'None'}</div>`).join('');const inv=S.inventory.map(id=>GEAR.find(g=>g.id===id)?.name).filter(Boolean).map(n=>`<span class="pill">${n}</span>`).join('')||'No items yet';const content=`<div class="wrap"><div class="card row space"><h1>🧙 Hero Profile</h1><button class="secondary" onclick="${fromModal?'closeModal();renderGame()':'mainMenu()'}">Back</button></div><div class="grid"><div class="card"><h2>${CLASSES[S.classKey].icon} ${escapeHtml(S.nickname)}</h2><p>${CLASSES[S.classKey].name} · Difficulty <span class="stars">${stars(CLASSES[S.classKey].stars)}</span></p><p>${CLASSES[S.classKey].desc}</p><div class="stat">Level ${S.level}<br>XP ${S.xp}/${xpNeeded()}<br>Coins ${S.coins}<br>Score ${S.score}<br>Best Streak ${S.bestStreak}</div></div><div class="card"><h2>Equipped Gear</h2>${equipped}<p>Bonuses: HP +${b.hp||0}, Damage +${b.damage||0}, XP +${Math.round((b.xp||0)*100)}%</p></div><div class="card"><h2>Inventory</h2>${inv}</div><div class="card"><h2>Badges</h2>${S.badges.length?S.badges.map(x=>`<div class="badge">🏅 ${x}</div>`).join(''):'No badges yet.'}</div></div><div class="card"><h2>Multiplication Mastery</h2>${masteryReport()}</div></div>`; if(fromModal){modalRoot.innerHTML=`<div class="modalOverlay"><div class="modal" style="max-width:900px">${content}<button onclick="closeModal();renderGame()">Back to Game</button></div></div>`}else screen(content)}
function masteryReport(){const rows=[];for(let n=0;n<=12;n++){let attempts=0,correct=0,total=0,levels={};for(let b=0;b<=12;b++){const m=S.mastery[`${n}x${b}`];attempts+=m.attempts;correct+=m.correct;total+=m.totalTime;levels[masteryLevel(`${n}x${b}`)]=(levels[masteryLevel(`${n}x${b}`)]||0)+1;}const acc=attempts?Math.round(correct/attempts*100):0;const avg=correct?(total/correct).toFixed(1):'—';rows.push(`<tr><td>${n}s</td><td>${attempts}</td><td>${acc}%</td><td>${avg}s</td><td>${Object.entries(levels).sort((a,b)=>b[1]-a[1])[0][0]}</td></tr>`)}return `<table class="masteryTable"><tr><th>Facts</th><th>Attempts</th><th>Accuracy</th><th>Avg Time</th><th>Main Level</th></tr>${rows.join('')}</table><p class="muted">Levels: Not Introduced, Learning, Developing, Proficient, Mastered, Automatic. Weak and slow facts appear more often; recent facts are blocked from repeating too soon.</p>`}
function localLeaderboard(){pushLeader();screen(`<div class="wrap"><div class="card row space"><h1>🏆 Local Leaderboard</h1><button class="secondary" onclick="mainMenu()">Main Menu</button></div><div class="card"><p class="warning">Local only. This leaderboard is only on this device/browser and is not shared online.</p>${S.leaderboard.slice(0,10).map((r,i)=>`<div class="stat">#${i+1} ${escapeHtml(r.nick)} — Score ${r.score}, Level ${r.level}, Bosses ${r.area}</div>`).join('')||'No scores yet.'}</div></div>`)}
function pushLeader(){S.leaderboard=S.leaderboard||[];S.leaderboard.push({nick:S.nickname,score:S.score,level:S.level,area:S.unlockedArea,date:new Date().toLocaleDateString()});S.leaderboard.sort((a,b)=>b.score-a.score);S.leaderboard=S.leaderboard.slice(0,20);save();}
function instructions(){screen(`<div class="wrap"><div class="card"><h1>How to Play</h1><p>Choose a class, answer multiplication facts, earn coins, buy gear and powers, defeat a boss at the end of each area, and unlock harder areas.</p><p>The game adapts by giving more practice on facts you miss or answer slowly, while avoiding repeating the same fact too often.</p><p>All progress is saved only in this browser.</p><button onclick="mainMenu()">Main Menu</button></div></div>`)}
function confirmQuit(){if(confirm('Return to main menu? Your current progress is saved.')){save();mainMenu();}}
function confirmReset(){if(confirm('Reset all local game progress on this device?')){localStorage.removeItem(SAVE_KEY);S=newState();mainMenu();}}
function closeModal(){modalRoot.innerHTML='';focusAnswer();}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
window.addEventListener('beforeunload',save);mainMenu();
