:root{
  --bg:#071222;--panel:#142642;--panel2:#1d3357;--line:#6d83bd;--text:#f7f9ff;--muted:#c7d2ea;
  --gold:#f5c84b;--green:#23c965;--blue:#16a7d8;--orange:#f7a53b;--red:#ef5350;--white:#ffffff;
  --radius:18px;--gap:10px;--top:62px;--bottom:54px;
  font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}
*{box-sizing:border-box} html,body{margin:0;height:100%;overflow:hidden;background:var(--bg);color:var(--text)}
button,input{font:inherit} button{cursor:pointer;border:0;border-radius:14px;background:#315080;color:var(--text);padding:10px 12px;font-weight:800;box-shadow:inset 0 -2px 0 rgba(0,0,0,.25)}
button:hover{filter:brightness(1.08)} button:disabled{opacity:.45;cursor:not-allowed}.danger{background:#8f3030}.good{background:#24854b}.gold{background:#9a741b}.ghost{background:#253856}.small{padding:7px 9px;font-size:13px}.wide{width:100%}
.app-shell{height:100dvh;height:100svh;max-width:1400px;margin:0 auto;padding:8px;display:flex;flex-direction:column;gap:var(--gap)}
.panel{background:linear-gradient(180deg,var(--panel2),var(--panel));border:3px solid var(--line);border-radius:var(--radius);padding:12px;min-height:0;overflow:hidden}.soft{border-color:#465a87;background:rgba(255,255,255,.04)}
.scroll{overflow:auto;-webkit-overflow-scrolling:touch;min-height:0}.row{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.between{justify-content:space-between}.muted{color:var(--muted)}.title{font-size:28px;font-weight:900;margin:0 0 8px}.big{font-size:40px;font-weight:950}.center{text-align:center}.hidden{display:none!important}

.start-screen{height:100%;display:grid;place-items:center;padding:12px;overflow:auto}.start-card{width:min(960px,100%);max-height:100%;overflow:auto}.class-grid,.card-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:10px}.class-card,.action-card,.item-card,.quest-card{background:rgba(255,255,255,.06);border:2px solid #45669d;border-radius:16px;padding:12px}.class-card h3,.action-card h3{margin:0 0 6px}.stars{color:var(--gold);letter-spacing:2px}.input{width:100%;padding:12px;border-radius:12px;border:2px solid #526da5;background:#0b1930;color:var(--text);font-weight:700;margin:8px 0}

.game{height:100%;display:grid;grid-template-rows:var(--top) minmax(0,1fr) var(--bottom);gap:var(--gap)}
.topbar,.bottombar{display:flex;align-items:center;justify-content:space-between;gap:8px;overflow:hidden}.status-chips{display:flex;gap:7px;align-items:center;flex-wrap:wrap;min-width:0}.chip{background:rgba(255,255,255,.08);border:1px solid #49638f;border-radius:999px;padding:6px 9px;font-size:13px;font-weight:800;white-space:nowrap}.nav-buttons{display:flex;gap:6px;flex-shrink:0}.layout{display:grid;grid-template-columns:minmax(190px,22%) minmax(320px,1fr) minmax(220px,25%);gap:var(--gap);min-height:0}.left-panel,.main-panel,.right-panel{min-height:0;display:flex;flex-direction:column;gap:8px}.main-content{flex:1;min-height:0}.hero-portrait{font-size:58px;text-align:center;line-height:1}.gear-list{display:grid;gap:5px}.gear-row{display:flex;justify-content:space-between;gap:6px;font-size:13px;background:rgba(255,255,255,.05);padding:6px;border-radius:9px}.stat-grid{display:grid;grid-template-columns:1fr 1fr;gap:5px}.stat{background:rgba(255,255,255,.06);border-radius:9px;padding:6px;text-align:center;font-size:13px}.right-split{display:grid;grid-template-rows:1fr 1fr;gap:8px;min-height:0;flex:1}.section-title{font-size:16px;font-weight:900;margin:0 0 6px}.mastery-mini,.coach-box{background:rgba(0,0,0,.14);border-radius:12px;padding:8px;margin-top:6px;font-size:13px}

.town-menu{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px}.action-card button{margin-top:8px}.battle-card{display:flex;flex-direction:column;gap:12px;align-items:center;justify-content:center;height:100%}.question{font-size:54px;font-weight:950}.answers{display:grid;grid-template-columns:repeat(2,minmax(120px,1fr));gap:10px;width:min(520px,100%)}.answers button{font-size:24px;padding:18px}.progressbar{width:100%;height:14px;background:#0a1427;border-radius:999px;overflow:hidden;border:1px solid #526da5}.progressbar span{display:block;height:100%;background:var(--green);width:0%}.summary-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:8px}.summary-stat{background:rgba(255,255,255,.06);border-radius:14px;padding:12px;text-align:center}.summary-stat b{display:block;font-size:26px}

.shop-grid,.inventory-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(170px,1fr));gap:8px}.item-card.locked{opacity:.55}.item-icon{font-size:30px}.item-card h4{margin:2px 0}.item-card p{margin:4px 0;font-size:12px;color:var(--muted)}.tabs{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:8px}.tabs button.active{background:#4b6ea9}.badge{display:inline-block;border-radius:999px;padding:3px 7px;font-size:11px;font-weight:900;background:#324d7b;margin:2px}.legend{display:flex;gap:8px;flex-wrap:wrap;font-size:12px}.legend span{display:inline-flex;align-items:center;gap:4px}.swatch{width:14px;height:14px;border-radius:4px;display:inline-block;border:1px solid #ddd}

.mastery-screen{height:100%;display:flex;flex-direction:column;gap:8px}.mastery-stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(110px,1fr));gap:8px}.mastery-table-wrap{flex:1;min-height:0;overflow:auto;-webkit-overflow-scrolling:touch;background:#fff;border-radius:10px;padding:4px}.mastery-table{border-collapse:collapse;width:100%;min-width:720px;color:#333;background:#fff}.mastery-table th,.mastery-table td{border:1px solid #d6d6d6;text-align:center;width:58px;height:48px;font-size:20px;font-weight:700}.mastery-table th{background:#94c9d8;color:#000;position:sticky;top:0;z-index:1}.mastery-table th:first-child{left:0;z-index:2}.mastery-table td:first-child,.mastery-table .rowhead{position:sticky;left:0;background:#94c9d8;color:#000;z-index:1}.m-new{background:#fff}.m-need{background:#f7a53b;color:#fff}.m-better{background:#16a7d8;color:#fff}.m-strong{background:#8bd477;color:#073b18}.m-mastered{background:#23c965;color:#fff}.m-cell small{display:block;font-size:15px;line-height:1}.crown{font-size:22px;color:#fff}.hour{font-size:19px}.warn{font-size:19px}

.overlay{position:fixed;inset:0;background:rgba(0,0,0,.58);display:grid;place-items:center;padding:12px;z-index:99}.modal{width:min(680px,100%);max-height:90dvh;display:flex;flex-direction:column;gap:8px}.toast{position:fixed;left:50%;bottom:70px;transform:translateX(-50%);background:#111d32;border:2px solid #6d83bd;border-radius:999px;padding:10px 16px;font-weight:900;z-index:120;box-shadow:0 12px 30px rgba(0,0,0,.4)}
.mobile-tabs{display:none}.mobile-drawer{display:none}

@media (max-width: 860px){
  .app-shell{padding:6px}.game{grid-template-rows:auto minmax(0,1fr) auto}.layout{grid-template-columns:1fr}.left-panel,.right-panel{display:none}.main-panel{min-height:0}.topbar,.bottombar{align-items:flex-start;flex-direction:column;padding:8px}.nav-buttons{width:100%;justify-content:space-between}.chip{font-size:12px;padding:5px 7px}.title{font-size:24px}.question{font-size:44px}.answers{grid-template-columns:1fr 1fr}.answers button{font-size:22px;padding:14px}.town-menu{grid-template-columns:1fr}.mobile-tabs{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;width:100%}.mobile-tabs button{font-size:12px;padding:8px 4px}.mobile-drawer{display:flex;position:fixed;left:6px;right:6px;bottom:6px;max-height:70dvh;z-index:80}.mastery-table{min-width:640px}.mastery-table th,.mastery-table td{height:44px;width:52px;font-size:18px}
}
@media (max-width: 430px){.big{font-size:32px}.answers{grid-template-columns:1fr}.mastery-table{min-width:590px}.mastery-table th,.mastery-table td{height:40px;width:48px;font-size:16px}}
